import type { Metadata } from "next";
import { Toaster } from "sonner";
import "./globals.css";
import AuthProvider from "@/providers/AuthProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={`antialiased`}>
          <main> {children}</main>
          <Toaster position="bottom-right" />
        </body>
      </AuthProvider>
    </html>
  );
}
